### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by sergeG** [zeenix/gps-share#12]
I try to build current git version:

$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/antoyo/dbus-macros-rs`
 Downloading serial v0.3.4
 Downloading libudev v0.2.0
 Downloading libc v0.2.36
 Downloading chan v0.1.20
 Downloading clap v2.29.2
 Downloading chan-signal v0.2.0
 Downloading dbus v0.5.4
 Downloading termios v0.2.2
 Downloading ioctl-rs v0.1.6
 Downloading libdbus-sys v0.1.2
 Downloading metadeps v1.1.2
 Downloading error-chain v0.10.0
 Downloading toml v0.2.1
 Downloading pkg-config v0.3.9
 Downloading libudev-sys v0.1.4
 Downloading rand v0.3.20
 Downloading atty v0.2.6
 Downloading strsim v0.6.0
 Downloading ansi_term v0.10.2
 Downloading bitflags v1.0.1
 Downloading textwrap v0.9.0
 Downloading vec_map v0.8.0
 Downloading unicode-width v0.1.4
 Downloading lazy_static v0.2.11
 Downloading bit-set v0.4.0
 Downloading bit-vec v0.4.4
   Compiling bit-vec v0.4.4
   Compiling bitflags v1.0.1
   Compiling lazy_static v0.2.11
   Compiling pkg-config v0.3.9
error: expected ident, found #
   --> /home/serge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
    |
423 |                               #[allow(deprecated)]
    |                               ^
    | 
   ::: /home/serge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
    |
4   | / bitflags! {
5   | |     /// This is the same `Flags` struct defined in the [crate level example](../index.html#example).
6   | |     /// Note that this struct is just for documentation purposes only, it must not be used outside
7   | |     /// this crate.
...   |
13  | |     }
14  | | }
    | |_- in this macro invocation

error: Could not compile `bitflags`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sergeG** [comment]
I use rust 1.19.0 under Gentoo ~amd64 system.

**Comment by sergeG** [comment]
Successfully build with rust 1.23.

**Comment by zeenix** [comment]
Thanks. I also added to README about rustc requirement now.

**Comment by sergeG** [comment]
Most important: everything works well, Sierra 7455, gentoo. Many thanks!

**Comment by zeenix** [comment]
Thanks for testing @sergeG !
