### ISSUE TITLE
Publish gps-share on crates.io

### ISSUE THREAD

**Issue by henry-nicolas** [zeenix/gps-share#24]
Dear @zeenix ,

Could you please consider publishing gps-share on crates.io?
We have some automation for Rust package managment, downstream at Debian, but it rely on crates.io to pull the crates.

That would ease the downstream packaging of gps-share for Debian and its derivative.

Thanks and best regards,

**Comment by zeenix** [comment]
Sure but I don't have time right now.

**Comment by zeenix** [comment]
@henry-nicolas I can find some time to roll out a release in the coming days but I'm very reluctant to do so w/o automated tests (given that I don't have time test it manually myself). If you (or anyone from your company) could help with the following, that'd greatly help me roll out the release:

1. basic e2e automated tests.
2. update of the readme, to reflect:
   * the recently added enhancements
   * dependencies (we no longer use dbus-rs crate)

**Comment by dcz-purism** [comment]
Which tests would you like to see contributed? I can see something like feeding gps-share a stream and seeing if it is multiplied correctly, but I don't really have an idea for testing a serial connection without dedicated test hardware.

**Comment by zeenix** [comment]
> Which tests would you like to see contributed? I can see something like feeding gps-share a stream and seeing if it is multiplied correctly, but I don't really have an idea for testing a serial connection without dedicated test hardware.

Right, you'll need to mock the hardware here. We already have some **very** basic test using the stdin source and we can continue to use that source for tests. Some tests with real hardware would be great too but they could be disabled by default (through a Cargo feature perhaps) so we don't run them in the CI but on dev machine, they can be used at least.

**Comment by zeenix** [comment]
@henry-nicolas Thanks to your engineers' help, we are now [live on crates.io](https://crates.io/crates/gps-share). :)

**Comment by henry-nicolas** [comment]
Thanks @zeenix that is great news and thanks @dcz-purism for the test cases implementation.
To be fair, I am just a community member, I work on packaging for downstream distros (ie: debian and derivates), so credits goes to dcz and yourself ;-)
