### ISSUE TITLE
Galileo and GLONASS support?

### ISSUE THREAD

**Issue by da2x** [zeenix/gps-share#5]
Are Galileo and GLONASS location sources supported? Should be documented. Shouldn’t also the project be renamed “gnss-share” for global navigation satellite systems or “satloc-share” for satellite location share?

**Comment by zeenix** [comment]
Are those GPS devices?

About the name, I don't think so? Anything wrong with the current name?

**Comment by da2x** [comment]
No, they’re competing/complimentary location-triangulating satellite networks. GPS is a network of satellites operated by the US government. Galileo is the European Union’s network of satellites, and GLONASS is Russia’s version. Modern satnavs chips will report GPS, GLONASS, and Galileo data separately. There are actually more networks out there than these three, most notably the BDS from China, but I don’t know anything about these and have never had a device that supports anyone but Galileo, GLONASS, and GPS.

A [USB test device](https://www.aliexpress.com/item/USB-GPS-GLONASS-receiver-GNSS-dual-mode-USB-output-support-GLONASS-BDS-compatible-alternative-BU-353SS/32815013668.html) that supports all three costs 7,40 USD with free shipping. 🛰 

The only thing wrong with the name is that it’s associated with one satellite network operated by the US government. GLONASS has higher accuracy in the enormous geographical area that is Russia, and Galileo has accuracy down to a few centimeters in Europe.

Ideally, the program should share the most accurate location data – regardless of which satellite network provides the most accurate location for the user.

**Comment by hadess** [comment]
I don't think the name is something interesting to focus on. It's been genericised to mean "satellite location technology", and you won't see any mentions of "GLONASS" or "Galileo" anywhere except in tech specs.

The specifics of hardware support stand, even though I'm fairly certain that there's no GPS-specifics in the NMEA protocol. Something to test out.

**Comment by da2x** [comment]
Pull request #7 adds support for Galieo, BeiDou, GLONASS, and GNSS (generic/mixed).

**Comment by da2x** [comment]
This issue now only tracks documentation and naming.

The naming discussing can be closed at @zeenix’s discretion.

The name `gps-share` falsely leaves the impression that the utility only support the GPS network. Which was almost true prior to pull request #7 (SBAS and QZSS were also supported.) The utility really should be called either `nmea-share` (after the protocol and information being shared, and how its advertised in service broadcast messages) or `gnss-share` (generic term for any satellite position system).
